### ISSUE TITLE
username and password 

### ISSUE THREAD

**Issue by hector-munachi** [CloudyPadmal/sysco-pos-react-front-end#8]
pls how can I get the login for the project? Thanks......

**Comment by CloudyPadmal** [comment]
Hello, the backend is at https://github.com/CloudyPadmal/sysco-pos-nodejs-server

**Comment by CloudyPadmal** [comment]
Hello, the backend is at https://app.swaggerhub.com/apis-docs/CloudyPadmal/Sysco-POS/1.0.3#/
